version: 0.2

phases:
  install:
    runtime-version:
      python: 3.12
  pre_build:
    commands:
      - echo Install dependencies
      - pip install -r requirements.txt
      - echo Install Playwright browser
      - python -m playwright install
  build:
    commands:
      - echo Running tests
      - pytest --html=reports/index.html
artifacts:
  files:
    - 'reports/**/*'
  discard-paths: yes
